<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="dawn" failures="1" tests="7" name="TestCases.ChooseReceivedPlace" time="126.986" errors="0" timestamp="2020-12-15T10:58:21 ICT" skipped="0">
  <testcase classname="TestCases.ChooseReceivedPlace" name="testMainSFWithFullInfor" time="17.110"/>
  <system-out/>
  <testcase classname="TestCases.ChooseReceivedPlace" name="testSuccessWithOnlyProvince" time="11.529"/>
  <system-out/>
  <testcase classname="TestCases.ChooseReceivedPlace" name="testSuccessWithoutFillTextboxAddress" time="13.350">
    <failure message="expected [Phường 15, Quận Bình Thạnh, Hồ Chí Minh] but found [TP. Hồ Chí Minh]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Phường 15, Quận Bình Thạnh, Hồ Chí Minh] but found [TP. Hồ Chí Minh]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestCases.ChooseReceivedPlace.testSuccessWithoutFillTextboxAddress(ChooseReceivedPlace.java:107)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSuccessWithoutFillTextboxAddress -->
  <system-out/>
  <testcase classname="TestCases.ChooseReceivedPlace" name="testFailWithoutChooseWard" time="14.734"/>
  <system-out/>
  <testcase classname="TestCases.ChooseReceivedPlace" name="testSuccessUpdateWithOnlyProvinceSubmitBefor" time="19.681"/>
  <system-out/>
  <testcase classname="TestCases.ChooseReceivedPlace" name="testSuccessUpdateByClickOnButonChange" time="19.259"/>
  <system-out/>
  <testcase classname="TestCases.ChooseReceivedPlace" name="testSuccessUpdateByClickOnDropBoxProvince" time="31.323"/>
  <system-out/>
</testsuite> <!-- TestCases.ChooseReceivedPlace -->
